name: Main

on:
  push:
    branches: [ "master" ]
  pull_request:
    types:
      - opened
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: setup gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.0.2
          arguments: wrapper

      - name: make gradlew executable
        run: chmod +x ./gradlew

      - name: run checkstyle
        run: ./gradlew checkstyleMain checkstyleTest

      - name: execute tests
        run: ./gradlew testAggregateTestReport --continue --parallel

      - name: generate coverage
        run: ./gradlew testCodeCoverageReport --continue --parallel